use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct MediaItem {
    pub name: String,
    pub category: String,
    pub tags: Option<Vec<String>>,
    pub image: String,
    pub desc: Option<String>,
    pub score: f32,
}

pub fn get_media() -> Vec<MediaItem> {
    vec![
        MediaItem {
            name: "Reze Arc".to_string(),
            category: "anime movie".to_string(),
            tags: None,
            image: "https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Chainsaw_Man_Reze_Arc_movie_poster.jpg/250px-Chainsaw_Man_Reze_Arc_movie_poster.jpg".to_string(),
            desc: Some("reze is an interesting character i wish her and denji were given more time. heavily carried by the fight scenes.".to_string()),
            score: 6.8,
        },
        MediaItem {
            name: "The Lighthouse".to_string(),
            category: "movie".to_string(),
            tags: None,
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVYD7y_upBOfFbA3sFgnn8v_EZr5CRgOGKUUwlrNG_T9oh2rD__Z9RRD-RsaLhnRBdrwTj&s=10".to_string(),
            desc: Some("it's completely black and white and this movie on 2 characters - how they conflict with their identities and situation that's happening in/out of reality".to_string()),
            score: 6.8,
        },
        MediaItem {
            name: "The Beginning Of Infinity".to_string(),
            category: "book".to_string(),
            tags: Some(vec!["currently reading".to_string()]),
            image: "https://u.cubeupload.com/namishhhh/thebeginningofinfini.jpeg".to_string(),
            desc: None,
            score: 10.0,
        },
        MediaItem {
            name: "Chainsaw Man".to_string(),
            category: "manga".to_string(),
            tags: Some(vec!["currently reading".to_string()]),
            image: "https://dwgkfo5b3odmw.cloudfront.net/manga/thumbs/thumb-105160-ChainsawMan_GN12_C1_Web-3-pGYFpo-UbtfnbBYz-wRXyA.jpg".to_string(),
            desc: Some("much better then the anime adaptation.".to_string()),
            score: 8.0,
        },
        MediaItem {
            name: "True Detective".to_string(),
            category: "tv".to_string(),
            tags: Some(vec!["nam's recommended".to_string()]),
            image: "https://m.media-amazon.com/images/M/MV5BYjgwYzA1NWMtNDYyZi00ZGQyLWI5NTktMDYwZjE2OTIwZWEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg".to_string(),
            desc: None,
            score: 9.8,
        },
        MediaItem {
            name: "Black Mirror".to_string(),
            category: "tv".to_string(),
            tags: Some(vec!["currently watching".to_string()]),
            image: "https://m.media-amazon.com/images/M/MV5BODcxMWI2NDMtYTc3NC00OTZjLWFmNmUtM2NmY2I1ODkxYzczXkEyXkFqcGc@._V1_.jpg".to_string(),
            desc: None,
            score: 9.0,
        },
        MediaItem {
            name: "Cowboy Bebop".to_string(),
            category: "anime".to_string(),
            tags: Some(vec!["peak".to_string()]),
            image: "https://upload.wikimedia.org/wikipedia/en/a/a9/Cowboy_Bebop_key_visual.jpg".to_string(),
            desc: Some("makes smoking look cool. 10/10".to_string()),
            score: 10.0,
        },
        MediaItem {
            name: "Frieren: Beyond Journey's End".to_string(),
            category: "anime".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BZTI4ZGMxN2UtODlkYS00MTBjLWE1YzctYzc3NDViMGI0ZmJmXkEyXkFqcGc@._V1_.jpg".to_string(),
            desc: Some("good world building. also a great filter for racists".to_string()),
            score: 7.0,
        },
        MediaItem {
            name: "Watchmen".to_string(),
            category: "book".to_string(),
            tags: None,
            image: "https://static.dc.com/dc/files/default_images/19084_400x600.jpg".to_string(),
            desc: Some("fantastic.".to_string()),
            score: 9.5,
        },
        MediaItem {
            name: "Solo Levelling".to_string(),
            category: "anime".to_string(),
            tags: Some(vec!["abysmal dogshit".to_string()]),
            image: "https://m.media-amazon.com/images/M/MV5BM2M4YzdkMTEtMjUyYy00ZWY0LWI5ODQtNGRkZWQ1MzU5MWM2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg".to_string(),
            desc: Some("insomnia final treatment".to_string()),
            score: 0.0,
        },
        MediaItem {
            name: "JoJo: Battle Tendency (part 2)".to_string(),
            category: "anime".to_string(),
            tags: Some(vec!["nam's recommended".to_string()]),
            image: "https://static.jojowiki.com/images/thumb/3/34/latest/20191015213237/Volume_11.jpg/800px-Volume_11.jpg".to_string(),
            desc: Some("my fav jojo part. not reviewing others (only watched till crusaders)".to_string()),
            score: 10.0,
        },
        MediaItem {
            name: "Death Note".to_string(),
            category: "anime".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_.jpg".to_string(),
            desc: Some("more you think about it, more it makes you realize how flawed the story is".to_string()),
            score: 6.0,
        },
        MediaItem {
            name: "Breaking Bad".to_string(),
            category: "tv".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_.jpg".to_string(),
            desc: None,
            score: 8.5,
        },
        MediaItem {
            name: "Eighty Six".to_string(),
            category: "anime".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BOWNmY2IzOGItMmQyNy00ZTM0LThiNjItODM3YzdkYjRlNWU1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg".to_string(),
            desc: Some("season 2 is much better, and the ending is really well wrapped up".to_string()),
            score: 8.6,
        },
        MediaItem {
            name: "Spy X Family".to_string(),
            category: "anime".to_string(),
            tags: Some(vec!["nam's recommended".to_string()]),
            image: "https://m.media-amazon.com/images/M/MV5BZDkwNjc0NWEtNzJlOC00N2YwLTk4MjktZGFlZDE2Y2QzOWI0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg".to_string(),
            desc: Some("really comfy".to_string()),
            score: 9.0,
        },
        MediaItem {
            name: "Love is War".to_string(),
            category: "anime".to_string(),
            tags: Some(vec!["nam's recommended".to_string()]),
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ8uWVp4-mIpRO0NQ2JdmRt1bS7gE-m-wUWiUvgkpmqSlH5mXlkbL9NkuCWbcx1wWpkwuI&s=10".to_string(),
            desc: Some("i usually don't watch romance anime because they make me feel lonely but this is way too over the top and funny. funny enough to make me laugh even during the rewatch".to_string()),
            score: 9.0,
        },
        MediaItem {
            name: "Love is War: Stairway to Adulthood".to_string(),
            category: "anime movie".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BMjE3OTAyZTAtNmUxNy00ZjA0LTgzZGEtZjYwMjk3NzNjYTdmXkEyXkFqcGc@._V1_QL75_UY281_CR5,0,190,281_.jpg".to_string(),
            desc: Some("some funny moments but does not live up to the hype".to_string()),
            score: 6.7,
        },
        MediaItem {
            name: "Arcane".to_string(),
            category: "tv".to_string(),
            tags: None,
            image: "https://m.media-amazon.com/images/M/MV5BYjA2NzhlMDItNWRmZC00MzRjLWE3ZjAtZjBlZDAwOWY2ODdjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg".to_string(),
            desc: Some("season 1 is great, season 2 is meh".to_string()),
            score: 8.5,
        },
    ]
}
